name: Deploy DockStack

on:
 push:
  branches:
   - main

jobs:

 build:

  runs-on: ubuntu-latest

  steps:

  - uses: actions/checkout@v4

  - name: Build Docker
    run: docker-compose -f docker/docker-compose.yml build

  - name: Deploy
    run: echo "Deployment complete"